import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import "./globals.css"
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";

export const metadata: Metadata = {
  title: "Mystery Message",
  description: "Generated by Development Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
      <AuthProvider>
          {children}
          <Toaster />
      </AuthProvider>
        </body>
    </html>
  );
}
